### ISSUE TITLE
CDK v2 support

### ISSUE THREAD

**Issue by aripalo** [aripalo/aws-cdk-github-oidc#11]
Release a new `v2` major with CDK v2 support

**Comment by dannysteenman** [comment]
+1 for cdkv2 support!

**Comment by dannysteenman** [comment]
It's possible to manage the construct for both versions (cdkv1 and cdkv2) using projen. Here you can find a good example on how to set it up: https://github.com/pahud/cdk-gitlab/blob/main/.projenrc.js
